### ISSUE TITLE
Was FrozenOrderedDict class dropped intentionally?

### ISSUE THREAD

**Issue by nikmolnar** [Marco-Sulla/python-frozendict#22]
OS version: 
macOS 11.1

Python3 version (python3 -V -V):
Python 3.9.2 (default, Mar 26 2021, 23:22:38) 
[Clang 12.0.0 (clang-1200.0.32.29)]

It looks like the `FrozenOrderedDict` class was dropped when moving code from `frozendict/__init__.py` to `frozendict/core.py` in d9b96d17b7a686a90f086cc4fcc32c028dbc6818. Was this intentional? I can't find any reference to this change anywhere than in the diff itself.

Thanks!

**Comment by Marco-Sulla** [comment]
Yes, `frozendict` is ordered by default as `dict` from Python 3.6. Is this a problem?

**Comment by Marco-Sulla** [comment]
It seems to me that `dict` supports `__reversed__`:

```
(venv_3_10) marco@buzz:~/sources/frozendict$ python
Python 3.10.0a3+ (heads/master-dirty:c8a7b8fa1b, Jan  1 2021, 14:43:59) 
[GCC 10.1.1 20200718] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from collections import OrderedDict
>>> a = OrderedDict({3:4, 1:2})
>>> list(reversed(a))
[1, 3]
>>> b = {3:4, 1:2}
>>> list(reversed(b))
[1, 3]
```

**Comment by lurch** [comment]
If I try the same in Python3.6 I get:
```
>>> list(reversed(b))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'dict' object is not reversible
```
(although I can obviously do `list(reversed(list(b)))` as a workaround)

**Comment by Marco-Sulla** [comment]
Do you want __reversed__ for `frozendict` pure py version and for c extension versions 3.6 and 3.7? Do actually **need** it or it's for completeness?

**Comment by lurch** [comment]
Well _personally_ I don't need it, and I'm not actually using `frozendict` at the moment anyway :wink:   The only reason I mentioned Python3.6 is because it's still the python3 used by Ubuntu 18.04 LTS which is supported until [April 2023](https://wiki.ubuntu.com/Releases).

(But also to add: when I have code that _relies_ on the ordering of a dictionary, I personally prefer to use `OrderedDict` rather than `dict` as IMHO it makes it more obvious that the dict-ordering is actually important)

**Comment by Marco-Sulla** [comment]
> I personally prefer to use OrderedDict rather than dict as IMHO it makes it more obvious that the dict-ordering is actually important)

IMHO `OrderedDict` is now obsolete, since it's slower and more memory consuming than `dict`. Since `frozendict` requires Python 3.6+, the order is preserved, and a FrozenOrderedDict is IMHO superfluous.

If there's a **real** need to implement `__reversed__` in `frozendict` 3.6 and 3.7, this is a different kettle of fish.

**Comment by jab** [comment]
> IMHO OrderedDict is now obsolete
>

No, it has additional (mutable) APIs that dict will never get and that
fulfill important use cases, e.g. move_to_end(…) and popitem(last=False).
Raymond Hettinger has talked about this at length, but here is a summary I
was able to find quickly:
https://mobile.twitter.com/raymondh/status/1379520632497442816

>

**Comment by Marco-Sulla** [comment]
Ok, well, people that used `FrozenOrderedDict` was never able to use this functions, since `FrozenOrderedDict` had [the same API](https://github.com/slezica/python-frozendict/blob/c5d16bafcca7b72ff3e8f40d3a9081e4c9233f1b/frozendict/__init__.py#L55) of `frozendict`. Simply, the internal dict was an OrderedDict and not a dict. `frozendict` never had `__reversed__`, `move_to_end()` or `popitem(last=False)`.

Furthermore, while `__reversed__` has sense in an immutable object, `move_to_end()` and `popitem()` no. I would introduce some of these mutable methods, but they will return a new object. Since this is not compatible with `dict` API, I want to introduce these methods in a future in the experimental `coold` class (available only in the C Extension and not available on Pypi now).

A compromise can be that I can reintroduce `FrozenOrderedDict` as a mere, deprecated, alias of `frozendict`, that will be removed definitively in a future.

**Comment by Marco-Sulla** [comment]
Closed https://github.com/Marco-Sulla/python-frozendict/commit/25f82172a296b94df8c7d28f283ed25032db9995
