### ISSUE TITLE
[FEATURE] build and publish precompiled binary wheels to PyPI

### ISSUE THREAD

**Issue by anthrotype** [Marco-Sulla/python-frozendict#38]
Hello,
thanks for this project!

It would be great if you set up Github Actions CI to build wheels for all supported python versions and platforms (Linux, Mac, Windows) and publish them (either automatically when pushing git tags, or manually if you prefer) to the Python Package Index (PyPI) so that `pip install frozendict` works without needing a compiler toolchain installed.
There's https://cibuildwheel.readthedocs.io/ that makes this relatively easy, it takes care of basically everything, as long a package can be built with `pip wheel`, which it does in your case.

Thanks for considering!

Cosimo

**Comment by Marco-Sulla** [comment]
Ciao. I think it's a good idea. I had already to set up a CI/CD on my TODO list. What I need is only the time.

**Comment by Marco-Sulla** [comment]
For now I added it on pushes only and it works:
https://github.com/Marco-Sulla/python-frozendict/actions/runs/1593577117

I would also add an action that creates a pure py package, without the C extension. On my machine, I can create it running `./setup.py py bdist_wheel`, since I modified my `setup.py` in such a way that, if the first argument is `py`, the C extension is not build.

How can I run that command as a Github Action?

**Comment by Marco-Sulla** [comment]
Unluckily, bug https://github.com/Marco-Sulla/python-frozendict/issues/41 evidenced that produced wheel does not work on Debian. Since Debian is THE Linux distro, I will not publish these binaries until I make them working with Debian.

If someone wants the C extension, (s)he can download the sdist package (the .tar.gz) and install it with `pip`

**Comment by anthrotype** [comment]
oh, that's a shame, thanks for trying though

> Unluckily, the binaries generated by cibuildwheel does not work, so I removed them from the current and next releases. I have to investigate.

How about you keep this issue open until you or some other contributor finds the time to investigate why this occurs?
Thanks again for considering.

**Comment by Marco-Sulla** [comment]
Why not?

**Comment by Marco-Sulla** [comment]
It seems the ABI is stable now. I close this report. Thank you again for signalling me cibuildwheel, anthrotype :)

**Comment by anthrotype** [comment]
thank you for fixing the issues and publishing the wheels to pypi 👍
